tabWidth: 4
trailingComma: none
arrowParens: avoid
plugins:
    - prettier-plugin-svelte
    - prettier-plugin-tailwindcss
    - "@ianvs/prettier-plugin-sort-imports"
overrides:
    - files: "*.svelte"
      options:
          parser: svelte
